### ISSUE TITLE
Login logic

### ISSUE THREAD

**Issue by Awuscan** [CaishenNefri/PRz-S4-Projekt-Grzybek#16]
Write the logic behind the login screen
Utworzenie funkcji logowania CAS
- [x] Stworzenie WebView
- [x] Przechwytywanie response z PROXY
- [x] Wywoływanie funkcji z Firebase
- [x] Utworzenie testowego usera
- [x] Parsowanie Base64 po stronie **CloudFunctions**
- [x] Parsowanie XML do JSON'a **CloudFunctions**
- [x] Dodanie danych usera z xml do bazy | do jego konta
- [x] Odsyłanie Custom Token do usera
- [x] Wysyłanie response z Androida do Cloud Functions
- [x] Odbieranie response z Androida na Clound Functions
- [x] Zalogowanie

https://github.com/mpenarprz/RandomUtils/tree/master/Misc/CASProxy

https://firebase.google.com/docs/auth/android/firebaseui

**Comment by CaishenNefri** [comment]
Utworzenie funkcji logowania CASu
- [ ] Stworzenie WebView
- [ ] Wysłanie danych użytkownika na serwer
- [ ] Dodanie użytkownika do bazy
- [ ] Odesłanie tokenu aplikacji
- [ ] Zalogowanie

https://github.com/mpenarprz/RandomUtils/tree/master/Misc/CASProxy

https://firebase.google.com/docs/auth/android/firebaseui

**Comment by CaishenNefri** [comment]
@mpenarprz 
Czy w response z Pańskiego proxy może znajdować się imię i nazwisko użytkownika? 
Mogę się mylić ale pamiętam jak pokazywał nam Pan funkcjonalność serwera proxy i były tam te dane (imię, nazwisku) w xml'u. Teraz serwer odpowiada bez takiej informacji. 
Taka dodatkowo informacja uprościła by znacznie proces dodawania użytkownika jak i jego weryfikację.

```javascript
<cas:serviceResponse xmlns:cas='http://www.yale.edu/tp/cas'>
	<cas:authenticationSuccess>
		<cas:user>65419@stud.prz.edu.pl</cas:user>
		
	<cas:attributes>
	  
	      
		  <cas:uid>65419</cas:uid>
	      
		  <cas:mail>65419@stud.prz.edu.pl</cas:mail>
	      
		  <cas:usos_id>159357</cas:usos_id>
	      
		  <cas:employeetype>student</cas:employeetype>
	      
		  <cas:registeredaddress>65419@stud.prz.edu.pl</cas:registeredaddress>
	      
		  <cas:departmentnumber>EF</cas:departmentnumber>
	      
	  
	</cas:attributes>

        
        
	</cas:authenticationSuccess>
</cas:serviceResponse>
```

**Comment by mpenarprz** [comment]
Może być tak że: dla kont studentów imię i nazwisko nie jest wymieniane... #borodo
