### ISSUE TITLE
Create app art

### ISSUE THREAD

**Issue by Awuscan** [CaishenNefri/PRz-S4-Projekt-Grzybek#18]
Create app logo and in-app icons

- [x] Ikona aplikacji - projekt graficzny
- [x] Logo aplikacji na ekranie logowania - projekt graficzny

**Comment by CaishenNefri** [comment]
@Zenigets siema. Dodałem Ci zadania do zrobienia. 
Na początku przydałoby się logo aplikacji

**Comment by CaishenNefri** [comment]
Na ten moment tworzony jest projekt ikony aplikacji:
![krasnal](https://user-images.githubusercontent.com/24476768/57238088-e422cf00-7028-11e9-9488-b7082ceda8b9.png)

**Comment by Zenigets** [comment]
![krasnal](https://user-images.githubusercontent.com/49253270/58190917-cb1f4c80-7cbd-11e9-8125-4d66332b0e07.png)

**Comment by Zenigets** [comment]
![grzybeknapis](https://user-images.githubusercontent.com/49253270/58191440-db83f700-7cbe-11e9-9f8b-9fa5fce09e5a.png)
Opcjonalnie zrobiłem napis
