### ISSUE TITLE
Link  Fabric

### ISSUE THREAD

**Issue by CaishenNefri** [CaishenNefri/PRz-S4-Projekt-Grzybek#21]
Podpiąć się pod znane i lubiane narzędzie do wyłapywania bugów oraz badania użyteczności aplikacji mobilnych – Fabric.
Założyć konto: https://fabric.io
Podpiąć swoje adresy mailowe oraz mój adres: mpenar@kia.prz.edu.pl jako betatesterów.

**Comment by Balowen** [comment]
Trzeba to skonsultować, bo użyliśmy FireBase crashlytics (zmigrowane fabric.io do firebase).
Niby działa.
