### ISSUE TITLE
Update logo.apk

### ISSUE THREAD

**Issue by CaishenNefri** [CaishenNefri/PRz-S4-Projekt-Grzybek#23]
Aktualizacja ikony aplikacji na ikonę utworzoną przez Maćka

**Comment by Zenigets** [comment]
![grzybek](https://user-images.githubusercontent.com/49253270/57974937-c0fd0580-79c0-11e9-9f94-6b2dd1415b32.png)
Grzybek logo aplikacji w formacie .png
