### ISSUE TITLE
Send Push Notifications 

### ISSUE THREAD

**Issue by CaishenNefri** [CaishenNefri/PRz-S4-Projekt-Grzybek#28]
Send Push Notifications to all users about new event

**Comment by Balowen** [comment]
Myślę nad takim rozwiązaniem:
każdy zalogowany użytkownik (czyli taki który widzi mainActivity) subskrybuje topic 'all'.
Przy dodawaniu wydarzenia do bazy, od razu wpisuje odpowiednie dane do powiadomienia push i rozsyłam do każdego subskrybenta topicu 'all' - a więc do każdego użytkownika Grzybka. 
Powinno dać się zrobić klikanie w powiadomienie i jakąś logikę - np. "dołącz do wydarzenia" ale to wiąże się z zapisywanie kto idzie na wydarzenie.
